version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user
#   - source:
#     destination:
# permissions:
#   - object:
#     pattern:
#     except:
#     owner:
#     group:
#     mode: 
#     acls:
#       -
#     context:
#       user:
#       type:
#       range:
#     type:
#       -
hooks:
  # ApplicationStop:
  #   - location: 
  #     timeout:
  #     runas:
  # BeforeInstall:
  #   - location: scripts/before_install.sh
  #     timeout: 300
  #     runas: ec2-user
  # AfterInstall:
  #   - location: scripts/after_install.sh    
  #     timeout: 300
  #     runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 60
      runas: ec2-user
  # ValidateService:
  #   - location:     
  #     timeout: 
  #     runas:
