# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo systemctl start mongod
    - run: npm ci
    - run: npm run build --if-present
    - run: (npm run start:test&)
    - run: npm test

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: AWS Deploy push
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy push \
          --application-name acebook \
          --description "This is a revision for the acebook-${{ github.sha }}" \
          --region us-east-2 \
          --ignore-hidden-files \
          --s3-location s3://continuously-eddie/acebook-${{ github.sha }}.zip \
          --source .
      - name: CodeDeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name acebook \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name production \
          --region us-east-2 \
          --file-exists-behavior OVERWRITE \
          --s3-location "bucket=continuously-eddie, bundleType=zip, key=acebook-${{ github.sha }}.zip"

        
