# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo systemctl start mongod
    - run: npm ci
    - run: npm run build --if-present
    - run: (npm run start:test&)
    - run: npm test

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo systemctl start mongod
      - run: npm ci
      - run: npm run build --if-present
      - run: mkdir ./zipfiles
      - run: zip ./zipfiles/acebook /home/runner/work/acebook-node-template/acebook-node-template
      - name: AWS S3 Deploy
      # You may pin to the exact commit or the version.
      # uses: vexelabs/s3-deploy@29658243b3016e198730d43165853077a37e953e
        uses: vexelabs/s3-deploy@v1
        with:
          # AWS Key ID to use
          aws-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS Secret Access Key to use
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS S3 Bucket name
          aws-bucket: continuously-eddie
          # AWS region to deploy to
          aws-region: us-east-2
          # Path prefix for the target S3 Key
          aws-key-prefix: # optional
          # Directory on Actions runner to upload to S3
          directory: ./zipfiles
          # Empties the old contents in the bucket before uploading the new files
          empty-bucket: false
      - name: CodeDeploy
      - run: |
        aws deploy create-deployment --application-name acebook --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name production --s3-location bucket=continuously-eddie, bundleType=zip,key=acebook.zip

        
